version: '3'

vars:
  # Dynamically read the Python version so you never hardcode it here
  PY_VERSION: 
    sh: cat .python-version

tasks:

#### Setup Tasks

  check-lock:
    desc: Verify lock file matches declared dependencies (fail if out-of-date)
    cmds:
      - uv lock --check   # check if uv.lock file is up to date with declared dependencies in pyproject.toml

  setup:python:
    desc: Set up Python environment
    cmds:
      - uv python install {{.PY_VERSION}}
      - uv sync --frozen  # Sync (creates .venv/) without updating the `uv.lock` file

  setup:pre-commit:  # Used by pre-commit hooks
    desc: Install pre-commit hooks
    cmds:
      - uv tool install pre-commit --with pre-commit-uv
      - uv run --no-sync pre-commit install    # Install all the pre-commit hooks listed in .pre-commit-config.yaml

  setup:
    desc: Complete developer onboarding setup
    cmds:
      - task: setup:python
      - task: setup:pre-commit

#### CI Tasks

  ci:lint:
    desc: Run Ruff via uv
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .

  typecheck:mypy: # Compare with other typecheckers like Astral's TY or pyrefly in 2027 since now they are immature
    desc: Run Mypy via uv
    cmds:
      - uv run mypy .

  typecheck:pyright:
    desc: Run static type analysis with Pyright
    cmds:
      - uv run pyright .
  
  test:
    desc: Run Pytest via uv
    cmds:
      - uv run pytest tests/

  ci:full-suite:
    desc: Run all checks
    cmds:
      - task: check-lock
      - task: ci:lint
      - task: typecheck:pyright   # default VS Code type checker used by Pylance VS Code extension, but lacks some features of Mypy
      - task: typecheck:mypy
      - task: test